### ISSUE TITLE
An realtime interactive dashboard recording COVID-19 outbreak in Japan

### ISSUE THREAD

**Issue by swsoyee** [Milano-R/erum2020-covidr-contest#16]
Submit your contributions by filling the following information

``` yaml
# Contribution's title, author, abstract
title: Interactive Dashboard for Real-Time Recording of COVID-19 Outbreak in Japan
author: Wei Su # can this be a person's name?
abstract: |
  The project is a website for real-time visualization of the COVID-19 
  epidemic in Japan, developed mainly using the R language with shiny and other
  open-source packages. It mainly shows various indicators including, 
  but not limited to, PCR test, positive confirmed, hospital discharge and death, 
  as well as trends in each prefecture in Japan, and there are also a variety of
  charts such as cluster network, new confirmed case in log scale for users' reference.

# Short name to be used in the website Gallery menu (can be the same as title)
menu_entry: COVID-19 Bulletin Board Japan
# URL of the public source code repository
repository: https://github.com/swsoyee/2019-ncov-japan
# Type of contribution and how it can be featured as gallery content
# Keep only the type and content relevant to your contribution
# For a Shiny app, provide its URL:
type: shiny
content: https://covid-2019.live/en
```

In addition:

- [x] Send an email to covidrcontest@erum.io (for further direct communication down the road)
     - Subject: "Submission to CovidR: Issue #00", where #00 is the number of this Issue
     - Content: A full link to this Issue
     - Optionally include your social media profiles (Twitter, LinkedIn, Facebook): we will use them to `@mention` you while sharing the contribution through our channels.
     
If you have questions specific to your submission, used the comments in this Issue.
