### ISSUE TITLE
COVID19 Data Visualization Monitor

### ISSUE THREAD

**Issue by shubhrampandey** [Milano-R/erum2020-covidr-contest#59]
Submit your contributions by filling the following information

``` yaml
# Contribution's title, author, abstract
title: COVID-19 Data Visualization Platform # title case
author: Shubhram Pandey # comma-separated
abstract: |
A new invisible enemy, only 30kb in size, has emerged and is on a killing spree around the world: 2019-nCoV, the Novel Coronavirus!  
This monitor was developed to make the data and key visualizations of COVID-19 trends available to everyone and also provide a platform to conduct a sentiment analysis of social media posts using Natural Language Processing (NLP).  
This monitor has 3 tabs: Dashboard, Comparison and Sentiments. The dashboard allows the user to view a complete picture of COVID-19 spread around the world. User can also click on any country in the map to view the numbers in that country. In comparison tab, user can compare the spread of COVID-19 in multiple countries in one view. Sentiment tab allows the user to run a sentiment analysis of trending hashtags of coronavirus on social media.  
The data used in this dashboard is from publicly available reliable and tested source like WHO , John Hopkins, etc.


# Short name to be used in the website Gallery menu (can be the same as title)
menu_entry: COVID19 Monitor
# URL of the public source code repository
repository: https://github.com/shubhrampandey/coronaVirus-dataViz
# Type of contribution and how it can be featured as gallery content
# Keep only the type and content relevant to your contribution
# For a Shiny app, provide its URL:
type: shiny
content: https://shubhrampandey.shinyapps.io/coronaVirusViz # e.g. my-app on shinyapps.io
```

In addition:

- [x] Send an email to covidrcontest@erum.io (for further direct communication down the road)
     - Subject: "Submission to CovidR: Issue #00", where #00 is the number of this Issue
     - Content: A full link to this Issue
     - Optionally include your social media profiles (Twitter, LinkedIn, Facebook): we will use them to `@mention` you while sharing the contribution through our channels.
     
If you have questions specific to your submission, used the comments in this Issue.
