### ISSUE TITLE
Covid-19 Italy Dashboard - eRum Contest 2020

### ISSUE THREAD

**Issue by VitoFanelli** [Milano-R/erum2020-covidr-contest#62]
Submit your contributions by filling the following information

``` yaml
# Contribution's title, author, abstract
title: Dashboard to monitor Covid-19 pandemy in Italy 
author: Vito Fanelli
abstract: |
  This dashboard allows to monitor Covid-19 pandemy in Italy. It based on daily data of Protezione Civile. The "Italy" section shows the number of total cases, actual cases, healed and deads at country level. It contains daily trends, moving averages and mortality rate. In "Region" section there are the same information at regional level.

# Short name to be used in the website Gallery menu (can be the same as title)
menu_entry: Covid-19 in italy
# URL of the public source code repository
https://github.com/VitoFanelli/covid-19-italy
# Type of contribution and how it can be featured as gallery content
# Keep only the type and content relevant to your contribution
# For a Shiny app, provide its URL:
type: shiny
content: https://vitofanelli1.shinyapps.io/Covid19Italy/
# For a general online-published resource (e.g. a website / report):
type: webpage
content: https://user.github.io/my-analysis # URL of the webpage
# For more complex / heterogeneous contributions, you can create a GitHub
# Gist (https://gist.github.com/) with the relevant information and pointers:
type: gist
content: <script...> # place here what you get from the "Embed" button
```

In addition:

- [x] Send an email to covidrcontest@erum.io (for further direct communication down the road)
     - Subject: "Submission to CovidR: Issue #00", where #00 is the number of this Issue
     - Content: A full link to this Issue
     - Optionally include your social media profiles (Twitter, LinkedIn, Facebook): we will use them to `@mention` you while sharing the contribution through our channels.
     
If you have questions specific to your submission, used the comments in this Issue.
