### ISSUE TITLE
Global Covid-19 Explorer - eRum 2020 CovidR Contest

### ISSUE THREAD

**Issue by tdesmedt-tdsgn** [Milano-R/erum2020-covidr-contest#78]
Submit your contributions by filling the following information

``` yaml
# Contribution's title, author, abstract
title: Global Cover-19 Explorer # title case
author: DataHive # comma-separated
abstract: |
  The Global Covid-19 Explorer is a shiny dashboard using interactive visualizations with innovative metrics to compare the Covid-19 burden in different countries.

# Short name to be used in the website Gallery menu (can be the same as title)
menu_entry: Covid19-Explorer
# URL of the public source code repository
repository: https://github.com/tdesmedt-tdsgn/Covid-Explorer
# Type of contribution and how it can be featured as gallery content
# Keep only the type and content relevant to your contribution
# For a Shiny app, provide its URL:
type: shiny
content: https://user.shinyapps.io/my-app # e.g. my-app on shinyapps.io
https://datahive.shinyapps.io/Covid19-Explorer/
```

In addition:

- [x] Send an email to covidrcontest@erum.io (for further direct communication down the road)
     - Subject: "Submission to CovidR: Issue #00", where #00 is the number of this Issue
     - Content: A full link to this Issue
     - Optionally include your social media profiles (Twitter, LinkedIn, Facebook): we will use them to `@mention` you while sharing the contribution through our channels.
     
If you have questions specific to your submission, used the comments in this Issue.
